version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
        steps:
          - checkout
          - run:
            name: Install dependencies
            command: npm install
          - run:
            name: Run tests
            command: npm test
    working_directory: ~/tmp
