version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
        steps:
          - checkout
          - run: npm install
          - run: npm test
    working_directory: ~/tmp
